# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4321e1ca63b643b0f549d75a55fa1bc9ae361e31cc4ab0a4b7aa5ac4a3028bede7023077acd39d4138a00e963588add5bb405d852b768289124e4431ecec4025

test:
  secret_key_base: 901e0b1cc89daabef0459e021b6a90f5f266fdd42ef647a313734789d4f02ccbe7c98d64dd54f9d13c1a35e898da362ba25080296f9d5506159610f3ec45dc28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
